spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flightsys_db?&useSSL=false&serverTimezone=UTC&&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: root
    password: 123456

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
    suffix: .html
    mode: HTML
    servlet:
      content-type: text/html; charset=utf-8
